services:
  db:
    image: lcaohoanq/snake_game_app:1.1.1
    container_name: snake_game
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
